# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d33dc4e28b4918d140bf39c1cc81f7cb8be13531d39a3cd5d4790ac55f184844831f105aa06c3e7f778cb0b1956e37dbb08baa15cfb0bf1603f260f775f2ad5

test:
  secret_key_base: 02be048effdf41af62267416c77a914772c04e46db028734c80982f2c939a5351bbd412c57e8d1c97bf118355adea3dba1d4095245c84c198953130a4c8797d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
